.\" Process this file with
.\" groff -man -Tutf8 mload.1
.\"
.TH LinuxShimeji 1 "2015-04-01" Linux "User Manuals"
.SH NAME
linux-shimeji \- Desktop mascot
.SH SYNOPSIS
.B linux-shimeji [
.B options
]
.SH DESCRIPTION
.B linux-shimeji
is a Linux port of the Shimeji mascot desktop program.
.SH FILES
.I ~/.config/linux-shimeji
.RS
Per user default configuration folder.
.SH AUTHOR
Francesco Di Baldassarre <f.dibaldassarre@gmail.com>

